### ISSUE TITLE
CoffeeScript too mainstream

### ISSUE THREAD

**Issue by gkz** [elving/brunch-with-hipsters#2]
You should consider using [LiveScript](http://gkz.github.com/LiveScript/) instead.

**Comment by jpadilla** [comment]
+1

**Comment by elving** [comment]
LOL

**Comment by gkz** [comment]
Also, underscore.js (here as lodash) is **way** too mainstream - LiveScript comes with a little library, I doubt you've heard of it, [prelude.ls](http://gkz.github.com/prelude-ls/).

**Comment by gkz** [comment]
If you want to call yourself brunch-with-hipsters you better commit to keeping with pre-post-nothing projects.
